<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="DefaultCustomerServiceTest" tests="6" skipped="0" failures="0" errors="0" timestamp="2015-06-01T22:43:05" hostname="Latitude" time="0.007">
  <properties/>
  <testcase name="getCustomerTest" classname="DefaultCustomerServiceTest" time="0.0"/>
  <testcase name="trackCustomerVisitParamsTest" classname="DefaultCustomerServiceTest" time="0.0"/>
  <testcase name="saveCustomerTest" classname="DefaultCustomerServiceTest" time="0.0"/>
  <testcase name="trackCustomerVisitTest" classname="DefaultCustomerServiceTest" time="0.0"/>
  <testcase name="getCustomerNullTest" classname="DefaultCustomerServiceTest" time="0.0"/>
  <testcase name="getCustomerParamTest" classname="DefaultCustomerServiceTest" time="0.0"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[[Test worker] INFO DefaultCustomerServiceTest - Assertion failure in method call... This is expected
[Test worker] INFO DefaultCustomerServiceTest - Assertion failure in method call... This is expected
[Test worker] INFO DefaultCustomerServiceTest - Assertion failure in method call... This is expected
]]></system-err>
</testsuite>
